"""integrate governance models

Revision ID: 42b7fdb6f7e7
Revises: 0001_initial
Create Date: 2026-10-03 20:19:16.528377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42b7fdb6f7e7'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=256), nullable=True),
    sa.Column('cpse_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cpse_id'), 'users', ['cpse_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=True),
    sa.Column('entity_id', sa.String(length=256), nullable=True),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=128), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('escalated_by_id', sa.Integer(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'EDITED', 'ESCALATED', name='review_status'), server_default='PENDING', nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'EDIT', 'ESCALATE', name='review_decision'), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('original_ai_classification', sa.String(length=128), nullable=True),
    sa.Column('ai_confidence', sa.Double(), nullable=True),
    sa.Column('ai_recommendation', sa.String(length=128), nullable=True),
    sa.Column('has_critical_conflict', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('critical_conflict_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_classification', sa.String(length=128), nullable=True),
    sa.Column('human_override_reason', sa.Text(), nullable=True),
    sa.Column('source_cpse_id', sa.String(length=64), nullable=True),
    sa.Column('target_cpse_id', sa.String(length=64), nullable=True),
    sa.Column('source_material_code', sa.String(length=256), nullable=True),
    sa.Column('target_material_code', sa.String(length=256), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'NORMAL', name='review_priority'), server_default='NORMAL', nullable=False),
    sa.Column('national_material_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['escalated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['national_material_id'], ['national_materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_match_id'), 'reviews', ['match_id'], unique=False)
    op.create_index(op.f('ix_reviews_priority'), 'reviews', ['priority'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_source_cpse_id'), 'reviews', ['source_cpse_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_target_cpse_id'), 'reviews', ['target_cpse_id'], unique=False)
    op.create_table('review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=64), nullable=True),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_history_id'), 'review_history', ['id'], unique=False)
    op.create_index(op.f('ix_review_history_review_id'), 'review_history', ['review_id'], unique=False)
    with op.batch_alter_table('cpse_material_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_code', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('source_match_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_cpse_material_mapping_source_match_id'), ['source_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cpse_material_mapping_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_cpse_material_mapping_users', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_cpse_material_mapping_matches', 'material_matches', ['source_match_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('national_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('cnmc',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=64),
                   existing_nullable=False)
        batch_op.alter_column('category',
                   existing_type=sa.VARCHAR(length=100),
                   type_=sa.String(length=256),
                   existing_nullable=True)
        batch_op.create_foreign_key('fk_national_materials_users_app', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_national_materials_users_cre', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('national_materials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_national_materials_users_app', type_='foreignkey')
        batch_op.drop_constraint('fk_national_materials_users_cre', type_='foreignkey')
        batch_op.alter_column('category',
                   existing_type=sa.String(length=256),
                   type_=sa.VARCHAR(length=100),
                   existing_nullable=True)
        batch_op.alter_column('cnmc',
                   existing_type=sa.String(length=64),
                   type_=sa.VARCHAR(length=50),
                   existing_nullable=False)
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('cpse_material_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cpse_material_mapping_matches', type_='foreignkey')
        batch_op.drop_constraint('fk_cpse_material_mapping_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cpse_material_mapping_status'))
        batch_op.drop_index(batch_op.f('ix_cpse_material_mapping_source_match_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('status')
        batch_op.drop_column('source_match_id')
        batch_op.drop_column('confidence')
        batch_op.drop_column('material_code')
    op.drop_index(op.f('ix_review_history_review_id'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_id'), table_name='review_history')
    op.drop_table('review_history')
    op.drop_index(op.f('ix_reviews_target_cpse_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_source_cpse_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_priority'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_match_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpse_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
